title: "@taybuddy"
author:
  name: Tay
  email: taytheanalyst@gmail.com
description: >
  Engineer and Data Analyst from Myanmar (Burma)
  
# Build settings
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

jekyll:
  post_order: descending

# Minima-specific settings
minima:
  skin: auto
  nav_pages:
    - blog.md
    - about.md
    - toolbox.md 
  social_links:
    - title: github
      icon: github
      url: "#"
    - title: x-twitter
      icon: x-twitter
      url: "#"

baseurl: ""
url: "https://taybuddy.github.io"

footer_content: "Â© 2026 Taybuddy. All rights reserved."