title: Tay Zar Lin 
author:
  name: Tay Zar Lin
  email: taytheanalyst@gmail.com
description: >
  Engineer and Data Analyst from Myanmar (Burma)
  
# Build settings
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Minima-specific settings
minima:
  skin: auto
  nav_pages:
    - blog.md
    - about.md
    - toolbox.md 
  social_links:
    - title: github
      icon: github
      url: "https://github.com/taybuddy"
    - title: x-twitter
      icon: x-twitter
      url: "https://x.com/tay_zar_lin"

baseurl: ""
url: "https://taybuddy.github.io"