title: "Taybuddy"

author:
  name: Tay
  email: taybuddy@example.com
description: >
  Iaculis massa nisl malesuada lacinia integer nunc posuere. 
  
# Build settings
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

jekyll:
  post_order: descending

# Minima-specific settings
minima:
  skin: auto
  nav_pages:
    - about.md
    - blog.md
    - toolbox.md 
  social_links:
    - title: github
      icon: github
      url: "#"
    - title: x-twitter
      icon: x-twitter
      url: "#"
    - title: linkedin       
      icon: linkedin     
      url: "#" 
  hide_site_feed_link: true

baseurl: ""
url: "https://taybuddy.github.io"

footer_content: "Â© 2026 Taybuddy. All rights reserved."