title: "@taybuddy"

author:
  name: Tay
  email: taybuddy@example.com
description: >
  A guy who is coffeeholic, data nerd, and has a passion for digital economic velocity
  
# Build settings
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

jekyll:
  post_order: descending

# Minima-specific settings
minima:
  skin: auto
  nav_pages:
    - about.md
    - blog.md
    - toolbox.md 
  social_links:
    - title: github
      icon: github
      url: "#"
    - title: x-twitter
      icon: x-twitter
      url: "#"

baseurl: ""
url: "https://taybuddy.github.io"

footer_content: "Â© 2026 Taybuddy. All rights reserved."

hide_site_feed_link: true